### ISSUE TITLE
Exit fullscreen on orientation change back to portrait

### ISSUE THREAD

**Issue by r-a-o** [clappr/clappr-ios#194]
I tried a bunch of things but couldn't get the player to exit fullscreen when device changes orientation back to portrait. I was able to achieve fullscreen on orientation change to landscape, but once the fullscreen takes over, the view controller's change back to portrait doesn't trigger to switch back. Any pointers on this would help.

**Comment by nabilsafatli** [comment]
Hello @r-a-o ,

Can you please check if you have the option fullscreen set as `true`?
This is the option: `kFullscreen`

There is an option where we let the app control this fullscreen option as well, that is `kFullscreenByApp`, with this option you should be able to make it possible to work with the orientation.
