### ISSUE TITLE
UX issue: Seek bar scrubber jumps back and forth on seek

### ISSUE THREAD

**Issue by r-a-o** [clappr/clappr-ios#195]
On seek, the scrubber jumps from seek position back to current play position before it finally jumps to seek position when player starts playing again. 

Ideal implement would be to show some sort of subtle animation on the indicator while maintaining the scrubber position till the player is ready to play again. 

Simpler implement where it maintains scrubber position and shows loader animation on the player is also a good experience imo.

**Comment by nabilsafatli** [comment]
Hello @r-a-o , we've updated the entire media control and this problem isn't happening anymore.
Please checkout our latest version of Clappr 👍
