### ISSUE TITLE
Hide iPhoneX bottom home bar indicator when in fullscreen

### ISSUE THREAD

**Issue by r-a-o** [clappr/clappr-ios#196]
The home button indicator of iPhoneX needs to be hidden on video fullscreen.

**Comment by nabilsafatli** [comment]
Hello @r-a-o ,

The next version of the Clappr will probably have this fixed, this is the [Pull Request](https://github.com/clappr/clappr-ios/pull/202).

**Comment by nabilsafatli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Clappr Issue]](https://trello.com/c/2SzO6DlF/187-clappr-issue)
