### ISSUE TITLE
Poster and Spinner doesn't go away if app is put to background during player initialisation

### ISSUE THREAD

**Issue by r-a-o** [clappr/clappr-ios#199]
If you put the app in background while the player(set to autoplay) is initialising, on foregrounding the app the video starts playing but the poster and spinner does not go away. 

Let me know if you need help reproducing this bug.

**Comment by nabilsafatli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Colocar o Clappr em background durante o loading prende o player](https://trello.com/c/vrffCcdy/1-colocar-o-clappr-em-background-durante-o-loading-prende-o-player)

**Comment by paulogama14** [comment]
@r-a-o thank you. Is this behavior still happening?
