### ISSUE TITLE
Seek back during live playback

### ISSUE THREAD

**Issue by r-a-o** [clappr/clappr-ios#248]
Is it possible to seek back while the player is playing a live video? I tried doing this and couldn't drag the seek bar.

**Comment by nabilsafatli** [comment]
Hello @r-a-o , if you take a look into the class `SeekbarView.swift` you will notice that the default on  the scrubber is `isUserInteractionEnabled` false.
You would need to override it in your own custom player, maybe in the future we can put an option for that in Clappr, but I am not sure about this in the roadmap.
