### ISSUE TITLE
Minimum Sample on ObjectiveC

### ISSUE THREAD

**Issue by albertoiglesias2001** [clappr/clappr-ios#327]
I'm starting to create a library for another language and I need just a minimum example on Objective-C to make the wrapper (this is required for this language) Cannot be Swift.

Can you put some little sample with objectiveC (wrapping the swift framwork).

I saw on source code have one create my Diego Marcon, but is not working or is too old.

I just need to instance the CLPlayer or Player with some URL.  Can you halp with this?

should be something like this, right?

```
#import "ViewController.h"
#import <Clappr/Clappr.h>

// NSURL *sourceURL = [NSURL URLWithString:@"http://clappr.io/highline.mp4"];
    
player =[Player init];
    NSLog(@"Version = %@",player.isFullscreen);

```

**Comment by barbosa** [comment]
@albertoiglesias2001  you have to pass a dictionary of options containing the media url as the value of `kSourceUrl` (as mentioned in https://github.com/clappr/clappr-ios#create) to the player init method.

Also, you have to `alloc/init` the player.

Do you have an url of a full repo containing what you're trying to do?

**Comment by albertoiglesias2001** [comment]
I'm putting something like this:

    player = [[Player alloc] initWithOptions:myDictionary];
  
    [player on:@"Clappr:playing" callback:^(NSDictionary * obj) {
        NSLog(@"%@",@"Clappr:playing");
       // [player setFullscreen:TRUE];
    }];
    
    [player on:@"Clappr:requestFullscreen" callback:^(NSDictionary * obj) {
        NSLog(@"%@",@"Clappr:requestFullscreen");
        [player setFullscreen:TRUE];
    }];
    
    [player attachTo:playerContainer controller:self];
    
    //[player play];

**Comment by barbosa** [comment]
And what error do you get?

**Comment by albertoiglesias2001** [comment]
Probably I will create on component side, to receive the correct boolean values, because on Objective-C is not allow to send boolean


    NSMutableDictionary *arrOptions = [[NSMutableDictionary alloc]init];
    
    [arrOptions addEntriesFromDictionary:@{@"posterUrl" : @"http://clappr.io/poster.png"}];
    [arrOptions addEntriesFromDictionary:@{@"sourceUrl" : @"http://clappr.io/highline.mp4"}];
    [arrOptions addEntriesFromDictionary:@{@"fullscreen" : [NSNumber numberWithBool:TRUE] }];
    [arrOptions addEntriesFromDictionary:@{@"fullscreenByApp" : [NSNumber numberWithBool:TRUE] }];

**Comment by rcavaltw** [comment]
Your code sound about right. A working example follows. But there is a caveat: we noticed that not all methods from the `Player` interface are available to objective-c. I've created the PR #328 to fix that. You can follow it or build from the PR's branch meanwhile.

```objective-c
#import "ViewController.h"

@import Clappr;

@interface ViewController ()

@property (nonatomic, strong) Player *player;

@end

@implementation ViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    NSDictionary *options = @{ @"sourceUrl": @"https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8" };

    _player = [[Player alloc] initWithOptions: options];
    [_player attachTo:self.view controller:self];

}

@end
```

**Comment by albertoiglesias2001** [comment]
Hello Caval,

   for sourceUrl ok, no have any problem, but what about :

fullscreenByApp  and   fullscreen ?

   
 

NSDictionary *options = @{ @"sourceUrl": @"https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_fmp4/master.m3u8" };
