### ISSUE TITLE
support multi resolution like youtube?

### ISSUE THREAD

**Issue by fukemy** [clappr/clappr-ios#348]
Hello, first thanks for your great library, i want to ask "does your library support to change resolution like youtube, ex: when low network trigger, i can change from 740 -> 480"

**Comment by paulogama14** [comment]
Hi @fukemy, thank you. The `AVPlayer` has a mechanism to change the resolution accordingly to the network capacity. But the way to provide the manifest has to provide multiple variants on server side. You can check more information [here](https://developer.apple.com/videos/play/wwdc2018/502/).
